-- FIFTYfifty - Space shooter using a probability mechanic.
-- Copyright (C) 2014  Evan A. Kosin

-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.

-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.

-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.

-- Base particle systems generated by Particle Edit 0.9.0:
-- https://love2d.org/forums/viewtopic.php?p=22125&sid=6b72f2445ca276bc6f1205239a353c2f#p22125

particle = {}

function particle:load()
	self.system = {
	  bufferSize = 100,
	  emissionRate = 5000,
	  lifetime = 3,
	  particleLife = 3,
	  color = { 255, 245, 205, 255, 255, 65, 0, 0 },
	  size = { 0.75 * (love.window.getWidth() / 1920), 0, 0 },
	  speed = { 0, 500 * (love.window.getWidth() / 1920) },
	  direction = 90,
	  spread = 360,
	  radialAcceleration = 100 * (love.window.getWidth() / 1920)
	}
	self.image = love.graphics.newImage("images/particle.png")
end

function particle:createSystem(x, y)
	local system = love.graphics.newParticleSystem( self.image, self.system.emissionRate )
	system:setPosition( x, y )
	system:setBufferSize( self.system.bufferSize )
	system:setEmissionRate( self.system.emissionRate )
	system:setEmitterLifetime( self.system.lifetime )
	system:setParticleLifetime( self.system.particleLife )
	system:setColors( unpack(self.system.color) )
	system:setSizes( unpack(self.system.size) )
	system:setSpeed( unpack(self.system.speed) )
	system:setDirection( math.rad(self.system.direction) )
	system:setSpread( math.rad(self.system.spread) )
	system:setRadialAcceleration( self.system.radialAcceleration )
	return system
end

playerParticle = {}

function playerParticle:load()
	self.system = {
	  bufferSize = 2000,
	  emissionRate = 5000,
	  lifetime = 7,
	  particleLife = 7,
	  color = { 255, 245, 205, 255, 255, 65, 0, 0 },
	  size = { 1.0 * (love.window.getWidth() / 1920), 0, 0 },
	  speed = { 0, 800 * (love.window.getWidth() / 1920) },
	  direction = 90,
	  spread = 360,
	  radialAcceleration = 0 * (love.window.getWidth() / 1920)
	}
	self.image = love.graphics.newImage("images/particle.png")
end

function playerParticle:createSystem(x, y)
	local system = love.graphics.newParticleSystem( self.image, self.system.emissionRate )
	system:setPosition( x, y )
	system:setBufferSize( self.system.bufferSize )
	system:setEmissionRate( self.system.emissionRate )
	system:setEmitterLifetime( self.system.lifetime )
	system:setParticleLifetime( self.system.particleLife )
	system:setColors( unpack(self.system.color) )
	system:setSizes( unpack(self.system.size) )
	system:setSpeed( unpack(self.system.speed) )
	system:setDirection( math.rad(self.system.direction) )
	system:setSpread( math.rad(self.system.spread) )
	system:setRadialAcceleration( self.system.radialAcceleration )
	return system
end

shotParticle = {}

function shotParticle:load()
	self.system = {
	  bufferSize = 50,
	  emissionRate = 5000,
	  lifetime = 1,
	  particleLife = 1,
	  color = { 255, 245, 205, 255, 255, 65, 0, 0 },
	  size = { 0.25 * (love.window.getWidth() / 1920), 0, 0 },
	  speed = { 0, 200 * (love.window.getWidth() / 1920) },
	  direction = 90,
	  spread = 360,
	  radialAcceleration = 25 * (love.window.getWidth() / 1920)
	}
	self.image = love.graphics.newImage("images/particle.png")
end

function shotParticle:createSystem(x, y)
	local system = love.graphics.newParticleSystem( self.image, self.system.emissionRate )
	system:setPosition( x, y )
	system:setBufferSize( self.system.bufferSize )
	system:setEmissionRate( self.system.emissionRate )
	system:setEmitterLifetime( self.system.lifetime )
	system:setParticleLifetime( self.system.particleLife )
	system:setColors( unpack(self.system.color) )
	system:setSizes( unpack(self.system.size) )
	system:setSpeed( unpack(self.system.speed) )
	system:setDirection( math.rad(self.system.direction) )
	system:setSpread( math.rad(self.system.spread) )
	system:setRadialAcceleration( self.system.radialAcceleration )
	return system
end

laserParticle = {}

function laserParticle:load()
	self.system = {
	  bufferSize = 600,
	  emissionRate = 5000,
	  lifetime = 1,
	  particleLife = 1,
	  color = { 255, 245, 205, 255, 255, 65, 0, 0 },
	  size = { 0.1 * (love.window.getWidth() / 1920), 0, 0 },
	  speed = { 0, 1000 * (love.window.getWidth() / 1920) },
	  direction = 90,
	  spread = 45,
	  radialAcceleration = 0 * (love.window.getWidth() / 1920)
	}
	self.image = love.graphics.newImage("images/particle.png")
end

function laserParticle:createSystem(x, y)
	local system = love.graphics.newParticleSystem( self.image, self.system.emissionRate )
	system:setPosition( x, y )
	system:setBufferSize( self.system.bufferSize )
	system:setEmissionRate( self.system.emissionRate )
	system:setEmitterLifetime( self.system.lifetime )
	system:setParticleLifetime( self.system.particleLife )
	system:setColors( unpack(self.system.color) )
	system:setSizes( unpack(self.system.size) )
	system:setSpeed( unpack(self.system.speed) )
	system:setDirection( math.rad(self.system.direction) )
	system:setSpread( math.rad(self.system.spread) )
	system:setRadialAcceleration( self.system.radialAcceleration )
	return system
end

failParticle = {}

function failParticle:load()
	self.system = {
	  bufferSize = 600,
	  emissionRate = 5000,
	  lifetime = 1,
	  particleLife = 1,
	  color = { 255, 245, 205, 255, 255, 65, 0, 0 },
	  size = { 0.1 * (love.window.getWidth() / 1920), 0, 0 },
	  speed = { 0, 1000 * (love.window.getWidth() / 1920) },
	  direction = 90,
	  spread = 360,
	  radialAcceleration = 0 * (love.window.getWidth() / 1920)
	}
	self.image = love.graphics.newImage("images/particle.png")
end

function failParticle:createSystem(x, y)
	local system = love.graphics.newParticleSystem( self.image, self.system.emissionRate )
	system:setPosition( x, y )
	system:setBufferSize( self.system.bufferSize )
	system:setEmissionRate( self.system.emissionRate )
	system:setEmitterLifetime( self.system.lifetime )
	system:setParticleLifetime( self.system.particleLife )
	system:setColors( unpack(self.system.color) )
	system:setSizes( unpack(self.system.size) )
	system:setSpeed( unpack(self.system.speed) )
	system:setDirection( math.rad(self.system.direction) )
	system:setSpread( math.rad(self.system.spread) )
	system:setRadialAcceleration( self.system.radialAcceleration )
	return system
end